# Generated by Django 4.1.7 on 2023-03-29 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='username', max_length=30)),
                ('image', models.ImageField(default='/static/image/user.png', upload_to='admin')),
                ('admin_bio', models.TextField(default='Bio', max_length=200)),
                ('phone_num', models.IntegerField(blank=True, default=0, null=True)),
                ('face_url', models.URLField(blank=True, default=0, null=True)),
                ('insta_url', models.URLField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('user_views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post', models.CharField(max_length=100)),
                ('new_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostsAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=60)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts-photo')),
                ('post_views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pieces', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(choices=[('كريم', 'كريم'), ('شامبو', 'شامبو'), ('ماكينات حلاقة', 'ماكينات حلاقة'), ('حمام كريم', 'حمام كريم'), ('مستحضرات', 'مستحضرات'), ('جل', 'جل')], max_length=30)),
                ('image', models.ImageField(upload_to='pro_image/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ShopActivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='activetion', max_length=30)),
                ('active', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zapayn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='zapayn-now', max_length=30, null=True)),
                ('members', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
