# Generated by Django 4.1.7 on 2023-04-01 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebaise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('offer', models.TextField(max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('range_continue', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('حمام كريم', 'حمام كريم'), ('شامبو', 'شامبو'), ('جل', 'جل'), ('كريم', 'كريم'), ('ماكينات حلاقة', 'ماكينات حلاقة'), ('مستحضرات', 'مستحضرات')], max_length=30),
        ),
    ]
