# Generated by Django 4.1.7 on 2023-04-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebaise', '0002_offer_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('جل', 'جل'), ('كريم', 'كريم'), ('حمام كريم', 'حمام كريم'), ('شامبو', 'شامبو'), ('مستحضرات', 'مستحضرات'), ('ماكينات حلاقة', 'ماكينات حلاقة')], max_length=30),
        ),
    ]
