# Generated by Django 4.1.7 on 2023-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebaise', '0003_offer_price_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='tiktok_url',
            field=models.URLField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('حمام كريم', 'حمام كريم'), ('كريم', 'كريم'), ('جل', 'جل'), ('مستحضرات', 'مستحضرات'), ('شامبو', 'شامبو'), ('ماكينات حلاقة', 'ماكينات حلاقة')], max_length=30),
        ),
    ]
